application: taipan3k
version: 0-1
runtime: python27       # Which runtime to use.
api_version: 1          # Which version of the API to use for that runtime.
threadsafe: true        # Whether or not to enable threading.
instance_class: F4      # Instance size to handle front-end requests.
default_expiration: 30d

# Third party libraries loaded from the App Engine environment.
libraries:
- name: jinja2
  version: "2.6"
- name: webapp2
  version: "2.5.1"

builtins:
- remote_api: on
- appstats: on

# Dispatch table from URL -> application instance or from URL -> static content.
handlers:

# Upload static scripts and HTML templates
- url: /
  static_dir: client
  login: required

# Provides interactive console for debugging purposes in production.
# This is equivalent to /_ah/admin in dev_app_server.
- url: /_ah/dev_console(/.*)?
  script: google.appengine.ext.admin.application
  login: admin
  secure: always
